import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: "#F9F9FB", 
    paddingHorizontal: 15,
  },
  header: { 
    fontSize: 28, 
    fontWeight: "700", 
    marginVertical: 15, 
    textAlign: "center",
    color: "#4B0082",
  },
  favoritesHeader: {
    fontSize: 28,
    fontWeight: "700",
    marginVertical: 15,
    textAlign: "center",
    color: "#4B0082",
  },
  input: {
    height: 50,
    borderColor: "#E0E0E0",
    borderWidth: 1,
    paddingHorizontal: 20,
    borderRadius: 25,
    marginBottom: 15,
    fontSize: 16,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    margin: 10,
  },
  searchTypeContainer: { 
    flexDirection: "row", 
    justifyContent: "center", 
    marginBottom: 15,
    
  },
  searchTypeButton: {
    paddingVertical: 10,
    paddingHorizontal: 25,
    borderWidth: 1,
    borderColor: "#4B0082",
    marginHorizontal: 8,
    borderRadius: 20,
  },
  activeButton: { 
    backgroundColor: "#4B0082",
  },
  searchTypeText: { 
    fontSize: 16,
    fontWeight: "600",
  },
  activeSearchTypeText: {
    color: "#fff",
  },
  inactiveSearchTypeText: {
    color: "#4B0082",
  },
  searchButton: {
    backgroundColor: "#ff6f61",
    padding: 14,
    borderRadius: 25,
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    margin: 10,
  },
  searchButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  list: { 
    paddingBottom: 100,
  },
  cardContainer: { 
    marginBottom: 12,
  },
  card: { 
    flexDirection: "row", 
    padding: 12, 
    borderRadius: 15,
    backgroundColor: "#fff",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
  },
  thumbnail: { 
    width: 80, 
    height: 80, 
    marginRight: 12,
    borderRadius: 8,
  },
  cardContent: { 
    flex: 1, 
    justifyContent: "center",
  },
  title: { 
    fontWeight: "700", 
    fontSize: 16,
    color: "#333",
    marginBottom: 4,
  },
  subtitle: { 
    color: "#666",
    fontSize: 14,
    marginBottom: 4,
  },
  albumText: {
    color: "#888",
    fontSize: 12,
  },
  favoritesButton: {
    position: "absolute",
    bottom: 30,
    right: 30,
    backgroundColor: "#ff6f61",
    padding: 16,
    borderRadius: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  detailCardContainer: {
    marginVertical: 20,
  },
  detailCard: { 
    alignItems: "center", 
    borderRadius: 15,
    padding: 20,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  detailImage: { 
    width: 220, 
    height: 220, 
    borderRadius: 12,
    marginBottom: 15,
  },
  detailTitle: { 
    fontSize: 24, 
    fontWeight: "700", 
    marginTop: 10,
    textAlign: "center",
    color: "#333",
  },
  detailSubtitle: { 
    fontSize: 18, 
    color: "#666",
    textAlign: "center",
    marginBottom: 10,
  },
  detailText: { 
    marginVertical: 6,
    fontSize: 16,
    color: "#444",
  },
  playButton: {
    flexDirection: "row",
    backgroundColor: "#4B0082",
    padding: 14,
    borderRadius: 25,
    marginVertical: 15,
    width: "100%",
    alignItems: "start",
    justifyContent: "start",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  disabledButton: {
    backgroundColor: "#a78bda",
  },
  playButtonContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  playIcon: {
    marginRight: 8,
  },
  playButtonText: { 
    color: "#fff", 
    fontWeight: "700",
    fontSize: 16,
  },
  ratingContainer: {
    width: "100%",
    alignItems: "center",
    marginVertical: 12,
  },
  ratingLabel: {
    fontSize: 16,
    marginBottom: 6,
    color: "#444",
    fontWeight: "600",
  },
  rating: { 
    paddingVertical: 10,
  },
  favoriteButton: {
    flexDirection: "row",
    padding: 14,
    borderRadius: 25,
    marginTop: 10,
    width: "100%",
    alignItems: "start",
    justifyContent: "start",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  addButton: {
    backgroundColor: "#ff6f61",
  },
  removeButton: {
    backgroundColor: "#ff3b30",
  },
  favoriteButtonContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  favoriteIcon: {
    marginRight: 8,
  },
  favoriteButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  favoriteCard: {
    borderRadius: 15,
    marginBottom: 12,
    padding: 12,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 3,
  },
  favoriteCardContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  favoriteTextContainer: {
    flex: 1,
    marginLeft: 12,
  },
  favoriteRating: {
    alignItems: "flex-start",
    marginTop: 6,
  },
  removeIcon: {
    padding: 10,
  },
  loader: {
    marginTop: 50,
  },
  emptyText: {
    textAlign: "center",
    color: "#666",
    fontSize: 16,
    marginTop: 30,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 100,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginTop: 20,
    marginBottom: 10,
    color: "#333",
  },
});